#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff-tree --no-commit-id --name-only HEAD -r  | grep -q "[^test]\.ts"; then
    
    color="\033[1;35m"
    echo "$color\n\nDocs require updating."

    exec < /dev/tty
    read -p "Should I update them and commit\? (y/n)" -n 1 

    if [[ $REPLY =~ ^[yY]$ ]]; then 
        yarn generate:docs
        git add docs
        git commit -m "docs: auto update"
        echo "$color\\nnDocs successfully updated\n\n"
    fi
fi