#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"



initial_status=$(git status)

yarn generate:docs

final_status=$(git status)

if [ "$initial_status" == "$final_status" ]
then
    exit 0
fi

git add -A

git commit -m "docs: auto-update" --no-verify

color="\033[1;35m"
echo "$color\n\nDOCS REQUIRED UPDATING BUT ARE NOW UP TO DATE. TRY AGAIN.\n\n"

exit 1
